In [3]:
#Empty stack
import numpy

stack = numpy.empty(shape = (12,6), dtype='object') #Initialize empty array (Panel stack)
print(stack)

[[None None None None None None]
 [None None None None None None]
 [None None None None None None]
 [None None None None None None]
 [None None None None None None]
 [None None None None None None]
 [None None None None None None]
 [None None None None None None]
 [None None None None None None]
 [None None None None None None]
 [None None None None None None]
 [None None None None None None]]


In [9]:
#Full Stack
import numpy as np


P1side = np.random.randint(6, size = (12,6)) 
print("3");
print("2");
print("1");
print("Channel!");
print(P1side);

3
2
1
Channel!
[[5 2 5 2 5 1]
 [1 4 5 4 4 4]
 [5 4 3 2 1 4]
 [0 3 4 4 0 2]
 [0 2 1 5 2 1]
 [2 3 0 4 0 5]
 [1 3 2 4 3 2]
 [4 5 1 5 4 0]
 [1 2 2 0 5 3]
 [2 3 5 1 0 0]
 [0 5 0 3 4 2]
 [3 5 2 2 0 4]]


In [15]:
#Formatted Stack
import numpy as np


P1side = np.random.randint(6, size=(12,6))